---
title: "論文の考察（Discussion）"
description: |
  スコーピング・レビューに基づく考察と今後の展望
output: distill::distill_article
---

## 1. 喫煙-DNAメチル化-アウトカムのパスウェイについて
今回レビューした論文の異質性（サンプルサイズや細胞、組織、手法）を鑑みても、*AHRR*や*GFI1*のDNAメチル化が妊娠中の母親の喫煙（X）と児の疾患（Y）との関連を媒介していることが示唆された。

これは、DNAメチル化率を単なるバイオマーカーとして利用するだけでなく、曝露と結果を結びつける媒介分析のメリットによるメリットだと考えられます。

今後は、媒介分析の方法論やより精密な曝露指標を用いた研究により、これらの結果の再現性などを検証するべきと考えています。


## 2. 媒介分析の方法論について
今回レビューした論文では、媒介分析について大きな「ばらつき」がありました。中には方法に媒介分析の実施すら書いてないものもありました。再現性など研究の質を担保するためにも、次の内容は少なくとも記述することが望ましいと考えています。

- どのようなモデルを使用したのか
- どのような共変量を使用したのか
- 結果の推定にはどのソフトウェア、プログラムを使用したのか
- 感度分析によってどの程度結果が変化するのか

特に、Cardenas A, et al. *Am J Epidemiol* (2019) やJordahl KM, et al. *Epigenetics* (2019) を参考に挙げています。


## 3. 複数の媒介変数に対する方法論
複数の媒介変数に対するアプローチは、エピジェネティックデータへのさらなる疫学研究のための議論のテーマとなるでしょう。

EWAS^[CpGサイトと結果変数との関連をゲノムワイドに探索する方法：エピゲノムワイド関連解析のこと]は大規模な疫学研究で一般的になってきており、いくつかの疾患や生活習慣の要因となる複数の異なるメチル化領域が見つかっています。

さらに、DNAのメチル化はその他のオミックス（ゲノミクスやプロテオミクスなど）と関連しているため、疾患の根底にある生物学的な複雑性に対して、高次元の媒介変数を扱う新しい方法論が必要となると考えています。

これらにアプローチしている研究として、Zhang H, et al. *Bioinformatics* (2016) を挙げています。

## 4. このレビューの限界点
1. 候補遺伝子研究（仮説検証型）とゲノムワイド関連研究（データ駆動型）が混合している。
2. 異なる細胞種による解析・研究成果をまとめている。
3. 多くの研究が特定の物質による単独の効果を推定している。
4. 我々の元々決めていたレビュー基準に適合する研究のみがレビューされている。

## 5. 最後に
このレビューでは、「関連を捉えてきた疫学」から「メカニズムにも迫る疫学」という発展をイメージしながら、その一つの方法論として媒介分析に注目しました。

現在、日本でも多くの疫学研究がゲノムをはじめ、より多様なオミックスデータを収集していることからこのような分子疫学研究がさらに発展する一助になれば幸いである。